import type { LocalizedToolContent, ToolContent } from './_types';

const makeContent = (zh: ToolContent, en: ToolContent): LocalizedToolContent => ({ zh, en });

const commonFaq = (zhQuestion: string, zhAnswer: string, enQuestion: string, enAnswer: string) => ({
  zh: [{ q: zhQuestion, a: zhAnswer }],
  en: [{ q: enQuestion, a: enAnswer }],
});

export const finalGradeNeededContent = makeContent(
  {
    name: '期末要考幾分計算器', short: '依目前加權得分與剩餘配分，估算期末評量至少需要幾分。',
    long: '輸入目標總成績、目前已取得的加權分數，以及剩餘評量權重，計算期末或最後一項評量需要達到的分數。',
    seoTitle: '期末要考幾分計算器｜成績目標與配分試算', seoDescription: '免費計算期末要考幾分，支援百分比與小數權重，清楚顯示已達標、可達成或需要超過滿分的情況。',
    keywords: ['期末要考幾分', '成績計算器', '加權成績', '目標分數'], capabilities: ['支援百分比與 0–1 小數權重', '顯示已達標、可達成與不可能達成狀態', '公式透明，方便核對課程配分'],
    contentSections: [{ heading: '怎麼使用', paragraphs: ['目標總成績是你想達到的總分；目前已取得的加權分數，是已完成評量對總成績的貢獻；剩餘權重則是期末或未完成項目占總成績的比例。', '若課程把每項評量列成百分比，請使用百分比模式。若你已把所有數值換成 0 到 1 的比例，才使用小數模式。不要把 80 分的原始成績誤填成 0.8，除非頁面模式與配分定義都一致。'], link: { prefix: '延伸閱讀：', label: '加權平均計算器', href: '/tools/weighted-average-calculator/', suffix: '可先核對各項配分。' } }, { heading: '解讀結果', paragraphs: ['結果是剩餘評量需要取得的原始分數估計，不代表校方一定採用相同的四捨五入、補考或及格規則。若結果高於滿分，代表在目前條件下無法只靠剩餘評量達標。'] }],
    instructions: ['填入目標總成績。', '填入目前已取得的加權分數。', '填入剩餘評量的權重，再按下計算。'], examples: [{ input: '目標 60、目前加權分數 42、剩餘權重 40%', output: '期末需要 45 分。' }],
    audience: ['學生', '教師', '家長'], faq: commonFaq('如果結果超過 100 分呢？', '代表依目前已取得的分數與剩餘配分，單靠最後評量無法達到目標；請重新核對配分或詢問授課單位。', 'What if the result is above 100?', 'It means the target cannot be reached from the remaining assessment under the entered weights. Check the grading weights or ask the course instructor.').zh,
    labels: { target: '目標總成績', earned: '目前已取得的加權分數', remaining: '剩餘權重', mode: '輸入模式', percent: '百分比（0–100）', fraction: '小數（0–1）', calculate: '計算', required: '剩餘評量需要分數', status: '狀態', 'already-met': '目前已達標', ok: '可達成', impossible: '需要超過滿分', formulaResult: '公式： (目標 − 已取得加權分數) ÷ 剩餘權重', invalid: '請檢查數值與剩餘權重。', notAvailable: '無法計算' }, formula: { expression: 'required = (target − earned weighted points) ÷ remaining weight', explanation: '所有輸入必須使用同一種權重表示法；本工具不會猜測你是否已經正規化。' }, educationApplication: '適合做課程規劃與情境試算，不取代學校正式成績紀錄。', disclaimer: '請依課程大綱確認配分、及格規則與四捨五入方式。', privacyNote: '計算在瀏覽器內完成，輸入不需上傳。',
  },
  {
    name: 'Final Grade Needed Calculator', short: 'Estimate the score needed on a final assessment from the remaining grade weight.',
    long: 'Enter a target course grade, weighted points already earned, and the remaining assessment weight to estimate the score needed on the final assessment.',
    seoTitle: 'Final Grade Needed Calculator | Weighted Grade Planning', seoDescription: 'Calculate the score needed on a final exam or remaining assessment with explicit percentage or fraction weight modes.', keywords: ['final grade calculator', 'grade needed calculator', 'weighted grade'],
    capabilities: ['Percentage and fraction weight modes', 'Clear achievable and impossible states', 'Transparent formula'], instructions: ['Enter the target grade.', 'Enter weighted points already earned.', 'Enter the remaining assessment weight and calculate.'], examples: [{ input: 'Target 60, earned 42, remaining weight 40%', output: 'You need 45 on the final assessment.' }], audience: ['Students', 'Teachers', 'Parents'], faq: commonFaq('What if the result is above 100?', 'The target cannot be reached from the remaining assessment with the entered weights. Check the grading policy.', '如果結果超過 100 分呢？', '代表依目前已取得的分數與剩餘配分，單靠最後評量無法達到目標；請重新核對配分。').en, labels: { target: 'Target grade', earned: 'Weighted points earned', remaining: 'Remaining weight', mode: 'Input mode', percent: 'Percent (0–100)', fraction: 'Fraction (0–1)', calculate: 'Calculate', required: 'Required remaining score', status: 'Status', 'already-met': 'Target already met', ok: 'Achievable', impossible: 'Above maximum', formulaResult: 'Formula: (target − earned weighted points) ÷ remaining weight', invalid: 'Check the values and remaining weight.', notAvailable: 'Not available' }, formula: { expression: 'required = (target − earned weighted points) ÷ remaining weight', explanation: 'Use one consistent weight representation; the calculator does not guess or silently normalize inputs.' }, disclaimer: 'Confirm the course grading policy, rounding, and passing rules.', privacyNote: 'Calculations run in your browser; inputs are not uploaded.',
  },
);

const itemLabels = { target: '目標', earned: '已取得', remaining: '剩餘權重', mode: '模式', percent: '百分比', fraction: '小數', calculate: '計算', required: '需要分數', status: '狀態', invalid: '請檢查輸入。', notAvailable: '無法計算', formulaResult: '公式已列於下方', simple: '簡易模式', bulk: '批次矩陣', p: '整體答對率 p', pHigh: '高分組答對率', pLow: '低分組答對率', n: '總人數', matrix: '每列一位受試者；每欄一題，請輸入 0 或 1', bulkHint: '可用逗號、空白或分號分隔。', items: '題數', difficulty: '難度 p', discrimination: '鑑別度 D', groups: '高分組／低分組', easy: '偏易', moderate: '中等', difficult: '偏難', kr20: 'KR-20', respondents: '受試者數', variance: '總分變異數', sumPQ: 'Σ(pᵢqᵢ)' };
const itemLabelsEn = { target: 'Target', earned: 'Earned', remaining: 'Remaining weight', mode: 'Mode', percent: 'Percent', fraction: 'Fraction', calculate: 'Calculate', required: 'Required score', status: 'Status', invalid: 'Check the inputs.', notAvailable: 'Not available', formulaResult: 'See the formula below', simple: 'Simple mode', bulk: 'Bulk matrix', p: 'Overall item difficulty p', pHigh: 'Upper-group proportion', pLow: 'Lower-group proportion', n: 'Total respondents', matrix: 'One respondent per row; one item per column, using 0 or 1', bulkHint: 'Use commas, spaces, or semicolons as separators.', items: 'Items', difficulty: 'Difficulty p', discrimination: 'Discrimination D', groups: 'Upper / lower group', easy: 'Easy', moderate: 'Moderate', difficult: 'Difficult', kr20: 'KR-20', respondents: 'Respondents', variance: 'Total-score variance', sumPQ: 'Σ(pᵢqᵢ)' };

export const itemAnalysisContent = makeContent(
  { name: '試題難度與鑑別度計算器', short: '用答對率與高低分組比較，快速檢查試題難度與鑑別度。', long: '簡易模式可直接輸入整體答對率、高分組答對率與低分組答對率；批次模式則以 0/1 作答矩陣計算每題的 p 值與 D 值。', seoTitle: '試題難度與鑑別度計算器｜p 值與 D 值', seoDescription: '免費計算試題難度 p 與鑑別度 D，支援單題試算與 0/1 作答矩陣批次分析。', keywords: ['試題難度', '鑑別度', '試題分析', 'p 值', 'D 值'], capabilities: ['單題簡易模式', '0/1 作答矩陣批次模式', '清楚區分難度與鑑別度的定義'], contentSections: [{ heading: '指標怎麼看', paragraphs: ['難度 p 是全體受試者答對比例；p 越高，代表題目越容易。鑑別度 D 是高分組答對率減去低分組答對率，反映題目能否區分整體表現較好的受試者。', '本工具的批次模式採總分排序後取上下 27% 作為高低分組。樣本很小、題目有猜測或測驗不只測一個構念時，請把結果當作篩選線索，不要單獨用來刪題。'], link: { prefix: '搭配使用：', label: '標準差計算器', href: '/tools/standard-deviation/', suffix: '協助檢查總分分布。' } }], instructions: ['選擇簡易模式或批次矩陣。', '輸入 0/1 作答資料或三個比例。', '按下計算並結合測驗目的解讀。'], examples: [{ input: 'p=.65、pHigh=.80、pLow=.40', output: '難度中等，鑑別度 D=.40。' }], audience: ['教師', '測驗研究者'], faq: [{ q: '難度 p 越高越好嗎？', a: '不一定。題目難度要配合測驗目的與整體分布，過易或過難都可能降低資訊量。' }], labels: itemLabels, formula: { expression: 'p = correct ÷ total; D = p(high) − p(low)', explanation: 'p 與 D 是不同指標；不要把高分組答對率直接當成整體難度。' }, educationApplication: '可在試後檢查題目是否過易、過難或缺乏區辨力。', disclaimer: '這是描述性試題分析，不是完整的信效度或公平性判定。', privacyNote: '矩陣在瀏覽器內處理。' },
  { name: 'Item Analysis Calculator', short: 'Estimate item difficulty and discrimination from correct-response rates.', long: 'Use simple mode for one item or paste a binary response matrix to calculate p and D for every item.', seoTitle: 'Item Analysis Calculator | Difficulty and Discrimination', seoDescription: 'Calculate item difficulty p and discrimination D from simple proportions or a binary response matrix.', keywords: ['item analysis', 'item difficulty', 'item discrimination'], capabilities: ['Simple single-item mode', 'Bulk 0/1 response matrix', 'Separate definitions for difficulty and discrimination'], instructions: ['Choose simple or bulk mode.', 'Enter proportions or a binary matrix.', 'Interpret the result with the assessment purpose in mind.'], examples: [{ input: 'p=.65, pHigh=.80, pLow=.40', output: 'Moderate difficulty and D=.40.' }], audience: ['Teachers', 'Assessment researchers'], faq: [{ q: 'Is a higher difficulty p always better?', a: 'No. The useful difficulty depends on the assessment purpose and score distribution.' }], labels: itemLabelsEn, formula: { expression: 'p = correct ÷ total; D = p(high) − p(low)', explanation: 'Difficulty and discrimination answer different questions and should not be conflated.' }, disclaimer: 'This is descriptive item analysis, not a complete validity, reliability, or fairness decision.', privacyNote: 'The response matrix is processed in your browser.' },
);

export const kr20Content = makeContent(
  { name: 'KR-20 信度計算器', short: '以 0/1 二分作答矩陣估算 Kuder–Richardson 20 內部一致性。', long: '貼上每列一位受試者、每欄一題的 0/1 矩陣，計算 KR-20、題數、受試者數與總分變異數。', seoTitle: 'KR-20 信度計算器｜二分題內部一致性', seoDescription: '免費用二分題作答矩陣計算 KR-20 信度，附公式、輸入檢查與解讀限制。', keywords: ['KR-20', '信度計算器', '二分題', '內部一致性'], capabilities: ['驗證 0/1 矩陣', '計算 KR-20 與總分變異數', '說明樣本與構念限制'], contentSections: [{ heading: '使用前先確認', paragraphs: ['KR-20 適用於每題以 0/1 計分的測驗。若題目是多分題、反向題尚未處理，或矩陣含有缺失值，請先依研究設計處理。', 'KR-20 反映內部一致性的某個面向，不等於內容效度、建構效度或測驗公平性；也不應只用一個門檻決定測驗是否可用。', '輸入前請確認每一列代表同一位受試者、每一欄代表同一題，且所有列的題數一致。若所有人總分都相同，總分變異數會接近零，此時信度估計沒有足夠資訊可供解讀。', '結果較適合作為測驗修訂的起點：可再檢查題目難度、鑑別度、題目是否測量同一構念，以及刪題後是否改變測驗內容範圍。'], link: { prefix: '延伸工具：', label: 'Cronbach’s Alpha 計算器', href: '/tools/cronbach-alpha-calculator/', suffix: '可比較適合連續或多分題資料的情境。' } }], instructions: ['每列輸入一位受試者的 0/1 作答。', '每欄輸入一題，欄數至少 2。', '按下計算並查看 KR-20 與總分變異數。'], examples: [{ input: '6 位受試者 × 5 題的 0/1 矩陣', output: '輸出 KR-20、樣本數、題數與變異數。' }], audience: ['教師', '研究生', '測驗研究者'], faq: [{ q: 'KR-20 高就代表測驗一定好嗎？', a: '不一定。它只描述二分題的內部一致性，仍需搭配測驗目的、內容與其他證據。' }, { q: '為什麼結果可能無法計算？', a: '若資料不是完整的 0/1 矩陣、題數不足，或總分沒有變異，公式中的必要資訊不足，工具會要求先修正資料。' }], labels: itemLabels, formula: { expression: 'KR-20 = k/(k−1) × [1 − Σ(pᵢqᵢ)/σ²ₓ]', explanation: 'k 是題數，pᵢ 是第 i 題答對比例，qᵢ=1−pᵢ，σ²ₓ 是總分的樣本變異數。' }, educationApplication: '適合在測驗初步分析階段檢查二分題的內部一致性。', disclaimer: '小樣本、低變異或多構念測驗可能讓估計不穩定；請勿單獨用 KR-20 做高風險決策。', privacyNote: '作答矩陣只在瀏覽器內計算。' },
  { name: 'KR-20 Reliability Calculator', short: 'Estimate internal consistency from a binary response matrix.', long: 'Paste one respondent per row and one binary item per column to calculate KR-20, item count, respondent count, and total-score variance.', seoTitle: 'KR-20 Reliability Calculator | Binary Items', seoDescription: 'Calculate Kuder–Richardson 20 reliability from a validated 0/1 response matrix, with formula and limitations.', keywords: ['KR-20 calculator', 'binary item reliability', 'internal consistency'], capabilities: ['Validate a binary response matrix', 'Calculate KR-20 and total-score variance', 'Explain interpretation limits'], instructions: ['Enter 0/1 responses with one respondent per row.', 'Use at least two items.', 'Calculate and review KR-20 with the variance.'], examples: [{ input: 'A 6-by-5 binary response matrix', output: 'KR-20, respondent count, item count, and variance.' }], audience: ['Teachers', 'Graduate students', 'Assessment researchers'], faq: [{ q: 'Does a high KR-20 prove that a test is good?', a: 'No. It describes one aspect of internal consistency and should be combined with content, construct, and fairness evidence.' }], labels: itemLabelsEn, formula: { expression: 'KR-20 = k/(k−1) × [1 − Σ(pᵢqᵢ)/σ²ₓ]', explanation: 'k is the item count, pᵢ is the proportion correct, qᵢ=1−pᵢ, and σ²ₓ is the sample variance of total scores.' }, disclaimer: 'Small samples, low variance, and multidimensional tests can make the estimate unstable.', privacyNote: 'The response matrix is processed in your browser.' },
);
